### ISSUE TITLE
Critical : Crash in PayuRechargeFragment.java 2000+ users are affected

### ISSUE THREAD

**Issue by riyaz** [payu-intrepos/Android-SDK#18]
http://crashes.to/s/f3f78df1cf2

**Comment by Franklin2412** [comment]
Please update to 4.1 - we have separated ui from sdk, in sdk 4.1 you can have your ui. please refer

https://github.com/payu-intrepos/Android-SDK

and sample app https://github.com/payu-intrepos/Android-SDK-Sample-App
