### ISSUE TITLE
Can't find PayUBaseActivity

### ISSUE THREAD

**Issue by DhavalsShah** [payu-intrepos/Android-SDK#20]
I am using PayU-release.jar library. As describe  on point 2.1. Non-Seamless: Using SDK’s Inbuilt UI,  intent pointing to PayUBaseActivity. But when I tried to point PayUBaseActivity.class in intent object. I can't find  PayUBaseActivity.class. Any help regarding  this will be valuable for me. Thanks

**Comment by VedavyasBhatNomadly** [comment]
I believe the sdkui (which contains `PayuBaseActivity`) is a separate module. But I don't know where to it get it from. Any help on this would be great.

**Comment by bharatindia** [comment]
Any Solution?

**Comment by VedavyasBhatNomadly** [comment]
I found the sdkui module (which is a gradle module) in the Android sample app (https://github.com/payu-intrepos/Android-SDK-Sample-App) and copied it into my project. It works fine.

**Comment by DhavalsShah** [comment]
@VedavyasBhatNomadly, How I got the payUmoney repo access? Please check these steps:
1) There are PayUmoney and PayUbiz. So be specific which sdk you want to use in your project? I assume that you want to use PayUmoney.
2)  You need to contact the technical support team of payUmoney in order to get the access of their sdk. See here what I did? I just dropped an email at **merchantcare@payumoney.com**	to request for their sdk.
3) They will respond you via email and ask the following details to provide sdk access:
- Git Hub Login ID
- Git Hub User ID
- Play Store App link
- Website URL
 So, these way your communication goes on and on through email/phone.
Contact Details: techsupport@payumoney.com. or 
call: 0124-6624-970/956 (10 am - 7 pm).(as on 16-Jan-2016 *This details might be changed). 
However this might be take some time. But this is the way, I followed in order to get the access of the payUmoney sdk. So, these seems like they haven't publicly exposed their payUmoney sdk yet.  Hope this might helpful to you.

**Comment by abahl817** [comment]
Their official youtube suggests the same what @VedavyasBhatNomadly said in his answer. Check it here: [https://www.youtube.com/playlist?list=PLVatFfdObuuxA3TM-00iSYfbyXxl0GMZ-](url)

**Comment by max-pro** [comment]
I'm using PayUbiz still I was getting an error. PayUBaseActivity not found.
