### ISSUE TITLE
PaymentOptionsActivity Missing Non Seamless Integration

### ISSUE THREAD

**Issue by aakashpronto** [payu-intrepos/Android-SDK#21]
Hi

Is there any update on the issue opened already for missing activity class.
We can not locate the PaymentOptionsActivity. 

We need to rollout urgently. Please update how to proceed.

`<activity ​android​:name=​"com.payu.sdk.PaymentOptionsActivity" ​android​:configChanges="orientation|keyboard|screenSize" ​/>
<activity ​android​:name=​"com.payu.sdk.ProcessPaymentActivity" ​android​:configChanges=​"orientation|screenSize" ​/>`

thanks,
Aakash

**Comment by mwshubham** [comment]
Have you resolved the issue @aakashpronto
