### ISSUE TITLE
How to integrate?

### ISSUE THREAD

**Issue by yokei15** [payu-intrepos/Android-SDK#22]
How to integrate this jar file into my project?? Is there is any dependency code too add??

**Comment by viswashsingh** [comment]
Hello,

You need to take access and get in touch with our integration team.
@Jitender Please help him in integration process.
Please let me know if any thing needed from my side.





*      Thanks & Regards*
* Viswash Pratap Singh*
* M : (+91) 8587996220*
*    Software Engineer*


On Thu, Feb 18, 2016 at 4:33 PM, yokei15 <notifications@github.com> wrote:

> How to integrate this jar file into my project?? Is there is any
> dependency code too add??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/payu-intrepos/Android-SDK/issues/22>.
>

-- 


PayUmoney hai #FaydeKiAadat <https://www.youtube.com/watch?v=zEW2ELLRKCM>

*Disclaimer:*


* "This message is intended only for the use of the addressee and may 
contain information that is privileged, confidential and exempt from 
disclosure under applicable law. If the reader of this message is not the 
intended recipient, or the employee or agent responsible for delivering the 
message to the intended recipient, you are hereby notified that 
any dissemination, distribution or copying of this communication is 
strictly prohibited. If you have received this e-mail in error, please 
notify us immediately by return e-mail and delete this e-mail and all 
attachments from your system."*

**Comment by yokei15** [comment]
@viswashsingh 
Can you please help me how to integrate in Android Studio these jar ?

**Comment by achavhan** [comment]
[PayUMoney SDK Integration Document.pdf](https://github.com/payu-intrepos/Android-SDK/files/137475/PayUMoney.SDK.Integration.Document.pdf)

**Comment by VedavyasBhatNomadly** [comment]
Is this jar not hosted somewhere? I would like to add this as a dependency through gradle.

**Comment by yokei15** [comment]
thanks mate @achavhan its working..

**Comment by AnandTraveller** [comment]
thanks dude @achavhan ur PDF really helped me to come out of confusions

**Comment by achavhan** [comment]
Payu guys mailed us latest payu sdk and said the one on the git hub is not the latest

**Comment by AnandTraveller** [comment]
Dude can you send that to me , my mail id anandindiaa@gmail.com Thanks in Advance

**Comment by achavhan** [comment]
@AnandTraveller  Sent

**Comment by VedavyasBhatNomadly** [comment]
In the document, in the "Import PayUmoney SDK as a module or Gradle Project" section, in section d it says browse to the sdk folder and import it as a gradle project. Where am I supposed to get that project from?

**Comment by achavhan** [comment]
@VedavyasBhatNomadly  give me ur email id i'll send it to you

**Comment by achavhan** [comment]
[PayUMoneySDK-Android-master (1).zip1.pdf](https://github.com/payu-intrepos/Android-SDK/files/137932/PayUMoneySDK-Android-master.1.zip1.pdf)   Remove 1.pdf
