### ISSUE TITLE
Hash param is missing error

### ISSUE THREAD

**Issue by VedavyasBhatNomadly** [payu-intrepos/Android-SDK#23]
I am trying to integrate PayU with the provided SDK (non-seamless approach) and when I try to invoke the `PayUBaseActivity`, I see a toast saying 'Mandatory param hash is missing', even though I have calculated the payment hash and set it in the `PaymentParams` object. 

After going through the code from the Android SDK sample app, I see that the test server you use returns a number of hash fields, which are set into the `PayuHashes` object, but I am only setting the payment hash. Is this the cause of the error? How do I generate the other hashes? I can't find this anywhere in your documentation.

**Comment by Shruti6293** [comment]
You need to generate Hash Key from you server you can find detail from below link : 
https://github.com/payu-intrepos/Documentations/wiki/4.-Server-Side

**Comment by VedavyasBhatNomadly** [comment]
This issue was resolved by setting the same calculated hash to the 'payment_related_details_for_mobile_sdk_hash' field.

**Comment by pranav2094** [comment]
@VedavyasBhatNomadly  can you please explain me.  I got the same issue. please help me.
Thank you in advance!
