### ISSUE TITLE
No proper documentation

### ISSUE THREAD

**Issue by HarshaMahadev** [payu-intrepos/Android-SDK#24]
I am working on implementing this SDK into my app, nothing works as per the documentation. Where am i suppose to get sdkui module?

**Comment by ashwindmk** [comment]
For documentation refer: https://github.com/payu-intrepos/Documentations/wiki/6.-Android-SDK-Integration

Sample app can be downloaded from https://github.com/payu-intrepos/Android-SDK-Sample-App/releases/

The sdkui module can be copied from the sample app.
