### ISSUE TITLE
<!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by balasasidhar** [payu-intrepos/Android-SDK#25]
I'm getting following error while using my test/production account's merchant key & salt. 
<!DOCTYPE of type java.lang.String cannot be converted to JSONObject 

It is working if I'm using Merchant Key & Salt from Sample App

**Comment by sasidhar678** [comment]
After looking into the SDK Source code I found that, it is working only with PayU ( https://payubiz.in ) not with PayUMoney ( https://www.payumoney.com ).

**Comment by santoshrokhade** [comment]
This error is coming for targetSdkVersion 25, but working fine for targetSdkVersion 23

**Comment by rahulchowdhury** [comment]
This got solved after setting the `ENVIRONMENT` in `PayUConfig` and then passing it instead of setting the `ENV` directly to the PayUBaseActivity `Intent`

**Comment by vivek50** [comment]
@rahulchowdhury  Any other solutions are available it's not working with PayUMoney..
