### ISSUE TITLE
Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.

### ISSUE THREAD

**Issue by venon123** [payu-intrepos/Android-SDK#26]
While trying to do for payment, I am getting the following error. Please help me I tried everything.
Scenario:
Go to credit/ debot card. Then enter test credentials (CREDIT CARD). Then it will stuck on a screen showing 'WE ARE PROCESSING YOUR TRANSACTION". 
And the log shows 
`05-27 15:00:53.746 8057-8057/com.payu.testapp I/chromium: [INFO:CONSOLE(5)] "The value "device-width;" for key "width" is invalid, and has been ignored.", source: https://mobiletest.payu.in/_payment (5)
05-27 15:00:53.746 8057-8057/com.payu.testapp I/chromium: [INFO:CONSOLE(5)] "The value "1.0;" for key "initial-scale" was truncated to its numeric prefix.", source: https://mobiletest.payu.in/_payment (5)
05-27 15:00:53.747 8057-8057/com.payu.testapp I/chromium: [INFO:CONSOLE(5)] "The value "1.0;" for key "maximum-scale" was truncated to its numeric prefix.", source: https://mobiletest.payu.in/_payment (5)
05-27 15:00:53.747 8057-8057/com.payu.testapp I/chromium: [INFO:CONSOLE(5)] "The value "0;" for key "user-scalable" was truncated to its numeric prefix.", source: https://mobiletest.payu.in/_payment (5)
05-27 15:00:53.747 8057-8057/com.payu.testapp I/chromium: [INFO:CONSOLE(5)] "Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.", source: https://mobiletest.payu.in/_payment (5)`

Please help me

**Comment by Ram8948** [comment]
i also have same issue. how to resolve  this issue .
Please help me

**Comment by satcomrastreadores** [comment]
i also have same issue. how to resolve this issue .
Please help me

**Comment by Gurubasappa** [comment]
i am getting this issue like warning!!

**Comment by nuwanhnk** [comment]
I'm getting the same error when i run protractor tests in headless chrome.

`"Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.",`
