### ISSUE TITLE
Mandatory param hash is missing error

### ISSUE THREAD

**Issue by shubhamvermadaffodil** [payu-intrepos/Android-SDK#27]
I get a "**_Mandatory param hash is missing_**" when i change the default key to my merchant key ,i do not understand what the issue behind it please suggest what should i do.

**Comment by VedavyasBhatNomadly** [comment]
I was getting this error because I was not setting the calculated hash into the 'payment_related_details_for_mobile_sdk_hash' field.

**Comment by rajchithathur** [comment]
Same error get while i am set all values also

**Comment by Jiks19** [comment]
same error get

**Comment by crestinfo** [comment]
I get a "Mandatory param hash is missing" when i change the default key to my merchant key ,i do not understand what the issue behind it please suggest what should i do.

Same issue.

**Comment by bhskr44** [comment]
Anyone solved this problem
