### ISSUE TITLE
Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by mwshubham** [payu-intrepos/Android-SDK#30]
I am currently implementing PayU India payment gateway for android.

I am getting following error:

`W: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
W:     at org.json.JSON.typeMismatch(JSON.java:111)
W:     at org.json.JSONObject.<init>(JSONObject.java:160)
W:     at org.json.JSONObject.<init>(JSONObject.java:173)
W:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:105)
W:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:52)
W:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
W:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W:     at java.lang.Thread.run(Thread.java:818)
D: ViewPostImeInputStage ACTION_DOWN`

here is a screen shot of the application. I seem like pay now is disabled. Please let us know the cause and feasible solution.

[http://www.awesomescreenshot.com/image/1468245/2ee508025fc727ea898fe0e84c377273](url)

Thanks,
Shubham Agarwal
Webkul Software Pvt. Ltd

**Comment by rahul21989** [comment]
facing the same issue. can you please help me regarding this issue ?

**Comment by SasiDev** [comment]
facing the same issue. can you please help me?

**Comment by abhiank** [comment]
I'm getting this issue too, in sdk version 4.4.3. Issue is closed now, how is this to be resolved?

**Comment by harshitaahuja** [comment]
I'm facing this issue too.. how to resolve this?

**Comment by hemant271189** [comment]
03-31 12:29:45.644 30388-14541/com.ehaat.app W/System.err: org.json.JSONException: Value (JSONObject.java:160)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err: at org.json.JSONObject.(JSONObject.java:173)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err: at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:105)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err: at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:52)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err: at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err: at java.lang.Thread.run(Thread.java:818)

Pleas help me how can i resolve this issue.
