### ISSUE TITLE
Fragment should be static such that they can be re-instantiated by the system.....

### ISSUE THREAD

**Issue by sandip31** [payu-intrepos/Android-SDK#33]
Getting error while signing an apk.
![pyu](https://cloud.githubusercontent.com/assets/12872544/22463927/782d9d8a-e7da-11e6-9099-356edd7ab5c4.jpg)

**Comment by hardikwingify** [comment]
Still not resolved

Anyway,
Add this in app gradle
    
`lintOptions {`
`            checkReleaseBuilds false`
`            abortOnError false`
`    }`

**Comment by jagadishg** [comment]
I'm getting the same problem. Any proper solution other than disabling lint?

**Comment by yashbhardwajqueppes** [comment]
@hardikm9850  Thanks for your valuable comment. It helps me, its working

**Comment by shaktisinh** [comment]
another option is

android {
        buildTypes {
            release {
                lintOptions {
                    disable 'MissingTranslation'
                }
            }
        }
    }
