### ISSUE TITLE
Unable to Launch PayUbaseActivity

### ISSUE THREAD

**Issue by ashokslsk** [payu-intrepos/Android-SDK#35]
public void launchSdkUI(PayuHashes payuHashes) {

        Intent intent = new Intent(this, **PayUBaseActivity**.class);
        intent.putExtra(PayuConstants.PAYU_CONFIG, payuConfig);
        intent.putExtra(PayuConstants.PAYMENT_PARAMS, mPaymentParams);
        intent.putExtra(PayuConstants.PAYU_HASHES, payuHashes);

        startActivityForResult(intent, PayuConstants.PAYU_REQUEST_CODE);

    }

// Implemented onActivityResult correctly. 
// The Hash is generated by API call from the internal server.

**Comment by himgupta229** [comment]
Any logs or stacktrace?
