### ISSUE TITLE
Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject 

### ISSUE THREAD

**Issue by rahul21989** [payu-intrepos/Android-SDK#36]

**Comment by PRAKHAR1997** [comment]
I got the same issue..

**Comment by NikhilBorad** [comment]
+1

**Comment by PRAKHAR1997** [comment]
Got the solution!! you have to carefully check whether you are using the test key with test environment.
For Test Environment, **merchantKey = "gtKFFx"** and set **int environment = PayuConstants.STAGING_ENV** which you can set as **payuConfig.setEnvironment(environment)**.
