### ISSUE TITLE
Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by prathameshbajare** [payu-intrepos/Android-SDK#38]
W/System.err: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:105)
W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:52)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by himgupta229** [comment]
Please check for issue #36

**Comment by hemant271189** [comment]
03-31 12:29:45.644 30388-14541/com.ehaat.app W/System.err: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:105)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at com.payu.india.Tasks.ValueAddedServiceTask.doInBackground(ValueAddedServiceTask.java:52)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-31 12:29:45.695 30388-14541/com.ehaat.app W/System.err:     at java.lang.Thread.run(Thread.java:818)


Pleas tell me how can i resolve this issue.

**Comment by prathameshbajare** [comment]
Please book an appointment for integration as all sdk's are depreciated and
payu only have working so don't waste time on those.

**Comment by himgupta229** [comment]
@hemant271189 Can you please check if you are using test key and test environment only.

**Comment by hemant271189** [comment]
Hi
 I am using test key and test  environment both. I have also check on
production   environment also.But always get same issue.
