### ISSUE TITLE
Affect Google Privacy Policy to payu sdkui for RECEIVE_SMS permission?

### ISSUE THREAD

**Issue by DarshanPatel23** [payu-intrepos/Android-SDK#43]
I got mail from Google to remove restricted permission RECEIVE_SMS. In my project, this permission writes only on pay u sdkui manifest file.

**Comment by ravitejaavv** [comment]
I am having same concern on RECEIVE_SMS permission? 
Any update on this? We have to resubmit the app by fixing permission issue by Jan 9th

**Comment by ananthpnj** [comment]
I am also facing the same issue., any solution for this issue?

**Comment by ravitejaavv** [comment]
> I am also facing the same issue., any solution for this issue?

https://support.google.com/googleplay/android-developer/answer/9047303

Check Exceptions ->
SMS-based financial transactions (e.g. 5 digit messages), and related activity including OTP account verification for financial transactions and fraud detection

SUBMIT PERMISSIONS DECLARATION FROM TO GOOGLE PLAY TEAM

**Comment by himgupta229** [comment]
Hi Everyone,  you can remove RECEIVE_SMS permission from the sdkui module and update the Custom Browser to 7.3.0 version. We have added support for SMS Retriever client in version 7.3.0 and removed RECEIVE_SMS permission.

**Comment by akshay-testpress** [comment]
@himgupta229 
implementation 'com.payumoney.sdkui:plug-n-play:7.3.0'
Failed to resolve: com.payumoney.sdkui:plug-n-play:7.3.0

**Comment by usmansagri** [comment]
how to remove SMS permissions from sdkui?

Im using 

implementation 'com.payumoney.core:payumoney-sdk:7.4.4'
    implementation  'com.payumoney.sdkui:plug-n-play:1.4.4'

**Comment by sranjith096** [comment]
Hi @himgupta229 
We reuse the SDKUI module from https://github.com/payu-intrepos/Android-SDK-Sample-App.

It uses custom browser V 7.3.0. Even after setting these below flags to `true`, the auto OTP read doesn't work.
https://github.com/payu-intrepos/Android-SDK-Sample-App/blob/master/sdkui/src/main/java/com/payu/payuui/Activity/PaymentsActivity.java#L259
https://github.com/payu-intrepos/Android-SDK-Sample-App/blob/master/sdkui/src/main/java/com/payu/payuui/Activity/PaymentsActivity.java#L260

Do we need to configure any other stuff to enable One Tap payments?

**Comment by ravitejaavv** [comment]
Hello,

Still i can see SMS permission in manifest-merger log. How do we remove SMS permissions from below libraries. 

com.payu.magicretry:magicretry:1.0.6] 
android.permission.RECEIVE_SMS

[com.payu.phonepe:phonepe-intent:1.0.0]
android.permission.READ_SMS

**Comment by himgupta229** [comment]
> how to remove SMS permissions from sdkui?
> 
> Im using
> 
> implementation 'com.payumoney.core:payumoney-sdk:7.4.4'
> implementation 'com.payumoney.sdkui:plug-n-play:1.4.4'

> .com.payu.custombrowser:payu-custom-browser:7.3.0 .For PnP sdk release visit https://github.com/payu-intrepos/payumoney-new-sample-app

**Comment by akshay-testpress** [comment]
Hey, right now I'm using 'com.payu.india:payu-sdk:4.4.3' which version will solve the SMS policy problem.

**Comment by himgupta229** [comment]
> Hello,
> 
> Still i can see SMS permission in manifest-merger log. How do we remove SMS permissions from below libraries.
> 
> com.payu.magicretry:magicretry:1.0.6]
> android.permission.RECEIVE_SMS
> 
> [com.payu.phonepe:phonepe-intent:1.0.0]
> android.permission.READ_SMS

Phonepe version is updated to 1.1.0 to comply with Google SMS Policy.

**Comment by himgupta229** [comment]
Use below dependencies of sdk which doesn't have SMS permission.

com.payu.custombrowser:payu-custom-browser:7.3.0
com.payu.phonepe:phonepe-intent:1.1.0

**Comment by qasim1911** [comment]
If you find which library is causing this then you can write this in your Android Manifest

<uses-permission
        android:name="android.permission.RECEIVE_SMS"
        tools:node="remove" />

This will prevent a library from asking this permission internally. Also please check if your library is functional without this permission after adding this line to your app manifest.

**Comment by SandeepJatthap** [comment]
I am using
