### ISSUE TITLE
magicretry_fragment.xml:121: AAPT: error: resource android:attr/android:progressBarStyleSmall not found       Getting this AAPT error.  Below are my gradle dependencies which I am currently using:implementation "com.payu.india:payu-sdk:4.4.8"     implementation 'com.payu.custombrowser:payu-custom-browser:7.5.0'

### ISSUE THREAD

**Issue by silpi19** [payu-intrepos/Android-SDK#51]

**Comment by silpi19** [comment]
Please help me with this.I am trying to migrate to androidx.

**Comment by himgupta229** [comment]
Could you try updating the CustomBrowser to 7.6.2 and payu-sdk to 4.7.0?

**Comment by silpi19** [comment]
yes @himgupta229 but same AAPT error is coming.Thanks for your quick reply.

**Comment by himgupta229** [comment]
Can you paste your build.gradle and stack trace of error that you are facing?

**Comment by silpi19** [comment]
Build.gradle:
apply plugin: 'com.android.library'

android {
    compileSdkVersion 30
    buildToolsVersion '29.0.2'

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 2
        versionName "2.0.1"
    }
    buildTypes {
        release {
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.payu.india:payu-sdk:4.7.0"
    implementation 'com.payu.custombrowser:payu-custom-browser:7.6.1'
    //implementation 'com.payu.samsungpay:samsungpay:1.0'
    //implementation 'com.android.support:appcompat-v7:27.1.1'
    //implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.payu.magicretry:magicretry:1.0.6'
    implementation 'com.payu.phonepe:phonepe-intent:1.1.0'
}


Error:
* What went wrong:
Execution failed for task ':religare:processStagingDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\SilpiMantraLabs\.gradle\caches\transforms-2\files-2.1\f6772157844560351dc4ac406c6d9162\jetified-magicretry-1.0.6\res\layout-v11\magicretry_fragment.xml:121: AAPT: error: resource android:attr/android:progressBarStyleSmall not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

**Comment by himgupta229** [comment]
> Build.gradle:
> apply plugin: 'com.android.library'
> 
> android {
> compileSdkVersion 30
> buildToolsVersion '29.0.2'
> 
> ```
> defaultConfig {
>     minSdkVersion 19
>     targetSdkVersion 30
>     versionCode 2
>     versionName "2.0.1"
> }
> buildTypes {
>     release {
>         minifyEnabled true
>         useProguard true
>         proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>     }
> }
> ```
> 
> }
> 
> dependencies {
> implementation fileTree(include: ['*.jar'], dir: 'libs')
> implementation "com.payu.india:payu-sdk:4.7.0"
> implementation 'com.payu.custombrowser:payu-custom-browser:7.6.1'
> //implementation 'com.payu.samsungpay:samsungpay:1.0'
> //implementation 'com.android.support:appcompat-v7:27.1.1'
> //implementation 'com.android.support:support-v4:27.1.1'
> implementation 'com.payu.magicretry:magicretry:1.0.6'
> implementation 'com.payu.phonepe:phonepe-intent:1.1.0'
> }
> 
> Error:
> 
> * What went wrong:
>   Execution failed for task ':religare:processStagingDebugResources'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> > Android resource linking failed
> > C:\Users\SilpiMantraLabs.gradle\caches\transforms-2\files-2.1\f6772157844560351dc4ac406c6d9162\jetified-magicretry-1.0.6\res\layout-v11\magicretry_fragment.xml:121: AAPT: error: resource android:attr/android:progressBarStyleSmall not found.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 33s

MagicRetry is no longer supported. Kindly remove its dependency and then try.

**Comment by silpi19** [comment]
Thanks now the error is gone.But I am facing errors with the magic retry implementation as in my project I have used this in many cases.Should I need to remove all these instances of magic retry?

**Comment by himgupta229** [comment]
Yes.

**Comment by silpi19** [comment]
ok thanks.
